- name: install and start nginx
  hosts: frontend
  become: yes #installing as root user
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
