- name: play level variables
  hosts: localhost
  connection: local #ansible is connecting to localhost, need to update in inventory file
  vars:
    COURSE: DEVOPS WITH AWS
    DURATION: 4 MONTHS
    TRAINER: SIVA
  tasks:
    - name: print the course info
      ansible.builtin.debug:
        msg: "COURSE name is {{ COURSE }}, {{ DURATION }}, {{ TRAINER }}"
