- name: grep for root
    #ansible.builtin.command: cat /etc/passwd | grep root -- using command module fails as it cannot go into the shell and execute the grep command
  ansible.builtin.shell: cat /etc/passwd | grep root
  register: command_output #the above command output is stored in the command_output 

- name: print the command_output
  ansible.builtin.debug:
    msg: "{{ command_output }}"

- name: redirect the output # using command module throws an error, but we can handle error by including ignore_errors as true.
  ansible.builtin.command: ls -ltr > /tmp/output.txt
  register: redirect_output
  #ignore_errors: true

- name: print redirect_output
  ansible.builtin.debug:
      msg: "{{ redirect_output }}"

- name: redirect the output using shell
  ansible.builtin.shell: ls -ltr > /tmp/output.txt
  register: redirect_output

- name: print redirect_output shell
  ansible.builtin.debug:
    msg: "{{ redirect_output }}"